apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rest-http-w0sz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rest-http-w0sz
    app.kubernetes.io/part-of: nodejs-rest-http
  name: nodejs-rest-http-w0szujyy
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: nodejs-rest-http-w0sz
    weight: null
status: {}
