apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rest-http-w0sz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rest-http-w0sz
    app.kubernetes.io/part-of: nodejs-rest-http
  name: nodejs-rest-http-w0sz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-rest-http-w0sz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-rest-http-w0sz
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/bgriggs-tenant/nodejs-rest-http/nodejs-rest-http-w0sz@sha256:f92497652f6fc020832a58685dcb4f1fe95b9344ec590e8906b4817b7b9645fe
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
