apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rest-http-w0sz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rest-http-w0sz
    app.kubernetes.io/part-of: nodejs-rest-http
  name: nodejs-rest-http-w0sz
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-rest-http-w0sz
status:
  loadBalancer: {}
